"""Turns a scan result dict into Markdown."""
from __future__ import annotations
import datetime

from .branding import watermark_line, PRODUCT_NAME, MAKER_NAME, MAKER_URL


def to_markdown(result: dict) -> str:
    lines = []
    lines.append(f"# {PRODUCT_NAME} Compliance Scan Report")
    lines.append("")
    lines.append(f"_{watermark_line()}_")
    lines.append("")
    lines.append(f"_Generated {datetime.date.today().isoformat()} · "
                  f"{result['files_scanned']} files scanned · "
                  f"{result['rules_evaluated']} rules evaluated · "
                  f"target markets: {', '.join(result['target_markets']) or 'unspecified'}_")
    lines.append("")
    lines.append("> This is an automated triage scan, not a legal audit. "
                  "Confidence scores indicate how reliable each finding is — "
                  "treat anything under 0.5 as a lead to investigate, not a fact.")
    lines.append("")

    lines.append("## Readiness by category")
    lines.append("")
    lines.append(f"**Overall readiness: {result['overall_readiness']}/100**")
    lines.append("")
    lines.append("| Regulation | Readiness |")
    lines.append("|---|---|")
    for cat, score in sorted(result["category_readiness"].items(), key=lambda x: x[1]):
        lines.append(f"| {cat} | {score}/100 |")
    lines.append("")

    if result["stale_rule_count"]:
        lines.append(f"⚠️ {result['stale_rule_count']} rule(s) haven't been "
                      f"re-verified in 180+ days — treat findings from them "
                      f"as extra-advisory. Run `--check-freshness` for details.")
        lines.append("")

    lines.append("## Findings (highest risk first)")
    lines.append("")
    if not result["findings"]:
        lines.append("No findings from the local rule set. This does not mean "
                      "the codebase is compliant — it means nothing in the "
                      "current knowledge base matched. Consider the "
                      "out-of-knowledge protocol for anything not covered.")
    for f in result["findings"]:
        stale_tag = " ⚠️ STALE RULE" if f["stale_rule"] else ""
        lines.append(f"### [{f['risk_score']}/100] {f['title']}{stale_tag}")
        lines.append(f"- **Regulation:** {f['regulation']} — {f['clause']}")
        lines.append(f"- **Location:** `{f['file']}:{f['line']}`")
        lines.append(f"- **Snippet:** `{f['snippet']}`")
        lines.append(f"- **Confidence:** {f['confidence']}")
        fe = f["fine_exposure"]
        lines.append(f"- **Estimated fine exposure:** ${fe['low_estimate']:,.0f}–${fe['high_estimate']:,.0f} "
                      f"(triage estimate, confidence-scaled from a ${fe['raw_range'][0]:,.0f}–${fe['raw_range'][1]:,.0f} statutory range)")
        lines.append(f"- **Why it matched:** {f['description']}")
        lines.append(f"- **Suggested fix:** {f['remediation']}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"_Report generated by **{PRODUCT_NAME}**, built by "
                  f"**{MAKER_NAME}** ({MAKER_URL}). Proprietary software — "
                  f"not for redistribution._")

    return "\n".join(lines)
